defmodule GrammarTest do
  use ExUnit.Case
  doctest Grammar

  test "generate regular grammar" do
    # e(e|f)*(f|g)*
    assert Grammar.generate_all(3, :S, [
      {[:S], [:e, :E]},
      {[:S], [:e]},
      {[:E], [:e, :E]},
      {[:E], [:f, :E]},
      {[:E], [:g, :F]},
      {[:E], [:e]},
      {[:E], [:f]},
      {[:E], [:g]},
      {[:F], [:f, :F]},
      {[:F], [:g, :F]},
      {[:F], [:f]},
      {[:F], [:g]}
    ], [:e, :f, :g], [:S, :E, :F]) ==
    [
      [:e],
      [:e, :e],
      [:e, :e, :e],
      [:e, :e, :f],
      [:e, :e, :g],
      [:e, :f],
      [:e, :f, :e],
      [:e, :f, :f],
      [:e, :f, :g],
      [:e, :g],
      [:e, :g, :f],
      [:e, :g, :g]
    ]

    # (a)*
    assert Grammar.generate_all(10, :S, [
      {[:S], []},
      {[:S], [:A]},
      {[:A], [:A, :a]},
      {[:A], [:a]}
    ], [:a], [:S, :A]) ==
    [
      [],
      [:a],
      [:a, :a],
      [:a, :a, :a],
      [:a, :a, :a, :a],
      [:a, :a, :a, :a, :a,],
      [:a, :a, :a, :a, :a, :a],
      [:a, :a, :a, :a, :a, :a, :a],
      [:a, :a, :a, :a, :a, :a, :a, :a],
      [:a, :a, :a, :a, :a, :a, :a, :a, :a],
      [:a, :a, :a, :a, :a, :a, :a, :a, :a, :a]
    ]
  end

  test "generate context-free grammar" do
    # (c)^N(d)^N, N >= 1
    assert Grammar.generate_all(9, :S, [
      {[:S], [:c, :S, :D]},
      {[:S], [:c, :d]},
      {[:D], [:d]}
    ], [:c, :d], [:S, :D]) ==
    [
      [:c, :c, :c, :c, :d, :d, :d, :d],
      [:c, :c, :c, :d, :d, :d],
      [:c, :c, :d, :d],
      [:c, :d]
    ]

    # Balanced parentheses
    assert Grammar.generate_all(6, :S, [
      {[:S], []},
      {[:S], [:P]},
      {[:P], [:P, :P]},
      {[:P], ["(", :P, ")"]},
      {[:P], ["(", ")"]}
    ], ["(", ")"], [:S, :P]) ==
    [
      [],
      ["(", "(", "(", ")", ")", ")"],
      ["(", "(", ")", "(", ")", ")"],
      ["(", "(", ")", ")"],
      ["(", "(", ")", ")", "(", ")"],
      ["(", ")"],
      ["(", ")", "(", "(", ")", ")"],
      ["(", ")", "(", ")"],
      ["(", ")", "(", ")", "(", ")"]
    ]
  end

  test "generate context-sensitive grammar" do
    # (1)^N(2)^N(3)^N, N >= 1
    assert Grammar.generate_all(9, :S, [
      {[:S], [1, :II, :III]},
      {[:S], [1, :S, :II, :III]},
      {[:III, :II], [:II, :III]},
      {[1, :II], [1, 2]},
      {[2, :II], [2, 2]},
      {[2, :III], [2, 3]},
      {[3, :III], [3, 3]}
    ], [1, 2, 3], [:S, :II, :III]) ==
    [
      [1, 1, 1, 2, 2, 2, 3, 3, 3],
      [1, 1, 2, 2, 3, 3],
      [1, 2, 3]
    ]
  end

  test "word generated by regular grammar" do
    # e(e|f)*(f|g)*
    assert Grammar.generates_word?([
      :e, :g
    ], :S, [
      {[:S], [:e, :E]},
      {[:S], [:e]},
      {[:E], [:e, :E]},
      {[:E], [:f, :E]},
      {[:E], [:g, :F]},
      {[:E], [:e]},
      {[:E], [:f]},
      {[:E], [:g]},
      {[:F], [:f, :F]},
      {[:F], [:g, :F]},
      {[:F], [:f]},
      {[:F], [:g]}
    ], [:e, :f, :g], [:S, :E, :F])
    assert not Grammar.generates_word?([
      :f, :g
    ], :S, [
      {[:S], [:e, :E]},
      {[:S], [:e]},
      {[:E], [:e, :E]},
      {[:E], [:f, :E]},
      {[:E], [:g, :F]},
      {[:E], [:e]},
      {[:E], [:f]},
      {[:E], [:g]},
      {[:F], [:f, :F]},
      {[:F], [:g, :F]},
      {[:F], [:f]},
      {[:F], [:g]}
    ], [:e, :f, :g], [:S, :E, :F])

    # (a)*
    assert Grammar.generates_word?([
      :a, :a, :a, :a, :a, :a
    ], :S, [
      {[:S], []},
      {[:S], [:A]},
      {[:A], [:A, :a]},
      {[:A], [:a]}
    ], [:a], [:S, :A])
    assert not Grammar.generates_word?([
      :S
    ], :S, [
      {[:S], []},
      {[:S], [:A]},
      {[:A], [:A, :a]},
      {[:A], [:a]}
    ], [:a], [:S, :A])
  end

  test "word generated by context-free grammar" do
    # (c)^N(d)^N, N >= 1
    assert Grammar.generates_word?([
      :c, :c, :c, :d, :d, :d
    ], :S, [
      {[:S], [:c, :S, :D]},
      {[:S], [:c, :d]},
      {[:D], [:d]}
    ], [:c, :d], [:S, :D])
    assert not Grammar.generates_word?([
      :c, :c, :c, :c, :d, :d, :d
    ], :S, [
      {[:S], [:c, :S, :D]},
      {[:S], [:c, :d]},
      {[:D], [:d]}
    ], [:c, :d], [:S, :D])

    # Balanced parentheses
    assert Grammar.generates_word?([
      "(", "(", ")", "(", ")", ")", "(", ")"
    ], :S, [
      {[:S], []},
      {[:S], [:P]},
      {[:P], [:P, :P]},
      {[:P], ["(", :P, ")"]},
      {[:P], ["(", ")"]}
    ], ["(", ")"], [:S, :P])
    assert not Grammar.generates_word?([
      "(", "(", "(", ")"
    ], :S, [
      {[:S], []},
      {[:S], [:P]},
      {[:P], [:P, :P]},
      {[:P], ["(", :P, ")"]},
      {[:P], ["(", ")"]}
    ], ["(", ")"], [:S, :P])
  end

  test "word generated by context-sensitive grammar" do
    # (1)^N(2)^N(3)^N, N >= 1
    assert Grammar.generates_word?([
      1, 1, 1, 2, 2, 2, 3, 3, 3
    ], :S, [
      {[:S], [1, :II, :III]},
      {[:S], [1, :S, :II, :III]},
      {[:III, :II], [:II, :III]},
      {[1, :II], [1, 2]},
      {[2, :II], [2, 2]},
      {[2, :III], [2, 3]},
      {[3, :III], [3, 3]}
    ], [1, 2, 3], [:S, :II, :III])
    assert not Grammar.generates_word?([
      1, 2, 2, 3, 3
    ], :S, [
      {[:S], [1, :II, :III]},
      {[:S], [1, :S, :II, :III]},
      {[:III, :II], [:II, :III]},
      {[1, :II], [1, 2]},
      {[2, :II], [2, 2]},
      {[2, :III], [2, 3]},
      {[3, :III], [3, 3]}
    ], [1, 2, 3], [:S, :II, :III])
  end
end
